### ISSUE TITLE
Using PID as owner value

### ISSUE THREAD

**Issue by rochacbruno** [py-sherlock/sherlock#10]
Hi, why not using the process PID as `Lock._owner` ?

It can be useful to use that values to check if the process that acquired the lock is still running.

**Comment by vaidik** [comment]
Hey @rochacbruno ,

That's a great idea. In distributed environments though, multiple processes can have the same PID. So this approach can work fine on a single box but might fail if you have processes running on multiple boxes, which should be more common IMHO.

Is my understanding correct? Would love to hear more and take this forward.

**Comment by judahrand** [comment]
Something similar to this is now implemented using the [filelock](https://py-filelock.readthedocs.io/en/latest/index.html) library as the backend.
