### ISSUE TITLE
Provide means to renew (refresh) the lock

### ISSUE THREAD

**Issue by cgst** [py-sherlock/sherlock#19]
For long running tasks gated by a lock, there needs to be a way to renew the lock.

**Comment by vaidik** [comment]
hey @cgst

apologies for not getting back to you in time. I was caught up with a lot of work at my current employer, with no time to maintain sherlock. I now have some time and can commit to improving sherlock.

Is this something you still need?

Also, just to be clear, do you need a way to automatically release a lock after a set period of time (TTL)?
