### ISSUE TITLE
How do you handle client disconnects?

### ISSUE THREAD

**Issue by adamsd5** [py-sherlock/sherlock#21]
Can you write up a summary detailing how you deal with clients that disconnect?  For example, Zookeeper provides ephemeral files that disappear when the client crashes.  However, this can also be a problem if there is a network interrupt and the client connection temporarily fails (releasing the lock).  Have you considered these client-side failure conditions?

**Comment by vaidik** [comment]
sherlock doesn't integrate with zookeeper just yet. And I don't see this been a problem with the existing backend support (i.e. memcached, redis and etcd).

But thanks for bringing this to my notice. I am going to add this to the zookeeper backlog to make sure that this case is covered.
