### ISSUE TITLE
Use `extra_requires` for the backend clients pip

### ISSUE THREAD

**Issue by kalyanaramansanthanam** [py-sherlock/sherlock#44]
Suggestion: Instead of requiring all 3 backend clients to be installed, please allow an option to only install the backend being used.

Relevant: https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by davidandreoletti** [comment]
@vaidik (ping)

#45 and #44 relate to the same issue: library users may not have/need all 3 supported backend and related libraries installed. As @kalyanaramansanthanam described above Python offers a solution to optional dependencies. The link seems broken but here is a very short summary: https://stackoverflow.com/a/45043494

Additionally, at runtime, only Lock classes whose dependencies is available at runtime should be declared (nice to have).

@judahrand Are you the new maintainer now ?

**Comment by davidandreoletti** [comment]
I have limited bandwidth for OSS projects and ended up not using this package. Another time perhaps :-)
