### ISSUE TITLE
`timeout=0` doesn't work

### ISSUE THREAD

**Issue by violuke** [py-sherlock/sherlock#54]
Firstly, thanks for the great package

I wanted to set `timeout=0` to effectively have just one attempt to get the lock, but the code is as follows:

```python
        if kwargs.get('timeout'):
            self.timeout = kwargs['timeout']
        else:
            self.timeout = _configuration.timeout
```

And so the `0` is Falsey and it instead uses `_configuration.timeout` when it shouldn't.

I'd suggest this be changed to:

```python
        if 'timeout' in kwargs:
            self.timeout = kwargs['timeout']
        else:
            self.timeout = _configuration.timeout
```

Thanks.

**Comment by judahrand** [comment]
Hey @violuke 

Do you want to submit that change in a PR? Looks like a reasonable solution!

**Comment by violuke** [comment]
Thanks @judahrand that's done :+1:
