### ISSUE TITLE
RedisLock.renew() is calling self._release_func() instead of self._renew_func()

### ISSUE THREAD

**Issue by sarobb** [py-sherlock/sherlock#66]
Line 510:

  self._release_func(keys=[self._key_name], args=[self._owner, self.expire])

... should be:

  self._renew_func(keys=[self._key_name], args=[self._owner, self.expire])

Confused me for the longest time until I looked at the code and saw what was happening!

Fantastic library, BTW, and exactly what I needed for a project. Very well-done code & documentaiton.

**Comment by judahrand** [comment]
I've pushed this fix and will aim to release it in the next few hours.

If you're interested in contributing I'd really appreciate it if you could look into improving the integration tests to better test `renew` and better catch this sort of thing.

**Comment by judahrand** [comment]
Fix is released in `v0.4.1`.
